ccflags-y += -Idrivers/soc/hisense/include

obj-y    += fs_sync.o hs_war_reboot.o
obj-$(CONFIG_HISENSE_SHOW_BOOTLOG)    += show_bootlog.o
obj-$(CONFIG_HS_POWERON_REASON)       += pon_off_reason.o
obj-$(CONFIG_HISENSE_SILENCE_REBOOT)  += hs_sil_reboot.o
