ccflags-y += -Idrivers/soc/hisense/include

obj-y       += bootinfo.o
obj-y += productinfo.o
obj-$(CONFIG_SAVE_AWAKEN_EVENT)       += awaken_sys_event.o
obj-y      += his_debug_base.o his_debug_attrs.o
