#
# Makefile for the hisense sensors drivers.
#
obj-$(CONFIG_HS_SNS_CM36686)	+= cm36686.o
obj-$(CONFIG_HS_SNS_CM32183)	+= cm32183.o
obj-$(CONFIG_HS_SNS_KXTJ9)	+= kxtj9.o
obj-$(CONFIG_HS_SNS_MC3XXX)	+= mc3xxx.o
obj-$(CONFIG_HS_SNS_AKM09911)	+= akm09911.o
obj-$(CONFIG_HS_SNS_APDS993X)	+= apds993x.o
obj-$(CONFIG_HS_SNS_ELAN_ALSPS)	+= epl259x.o
obj-$(CONFIG_HS_SNS_CM3232)	+= cm3232.o
obj-$(CONFIG_HS_SNS_HALL)	+= hall.o
obj-$(CONFIG_HS_SNS_SI1133)    += si1133.o
obj-$(CONFIG_HS_SNS_TMD2725)	+= ams_tmd2725.o ams_i2c.o
obj-$(CONFIG_HS_SNS_TMD3702)	+= ams_tmd3702.o ams_i2c.o
obj-$(CONFIG_HS_SNS_STK3X1X)	+= stk3x1x.o
obj-$(CONFIG_HS_SNS_STK3X3X)	+= stk3x3x.o
obj-$(CONFIG_HS_SNS_A96T346) += A96T346_sensor_class.o
